"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=['new.qml', 'HomeForm.ui.qmlc'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
